// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Fonts fonts = _Fonts._();
  static final _Images images = _Images._();
}

@immutable
final class _Fonts {
  _Fonts._();

  final String tajawal_black_ttf = 'assets/fonts/Tajawal-Black.ttf';
  final String tajawal_bold_ttf = 'assets/fonts/Tajawal-Bold.ttf';
  final String tajawal_extrabold_ttf = 'assets/fonts/Tajawal-ExtraBold.ttf';
  final String tajawal_extralight_ttf = 'assets/fonts/Tajawal-ExtraLight.ttf';
  final String tajawal_light_ttf = 'assets/fonts/Tajawal-Light.ttf';
  final String tajawal_medium_ttf = 'assets/fonts/Tajawal-Medium.ttf';
  final String tajawal_regular_ttf = 'assets/fonts/Tajawal-Regular.ttf';
}

@immutable
final class _App_icons {
  _App_icons._();

  final String arrow_back_svg = 'assets/images/app_icons/arrow_back.svg';
  final String buy_cart_svg = 'assets/images/app_icons/buy_cart.svg';
  final String cart_svg = 'assets/images/app_icons/cart.svg';
  final String favourite_svg = 'assets/images/app_icons/favourite.svg';
  final String heart_svg = 'assets/images/app_icons/heart.svg';
  final String home_svg = 'assets/images/app_icons/home.svg';
  final String icon_search_small_svg =
      'assets/images/app_icons/icon_search_small.svg';
  final String logo_png = 'assets/images/app_icons/logo.png';
  final String search_svg = 'assets/images/app_icons/search.svg';
  final String share_svg = 'assets/images/app_icons/share.svg';
  final String sort_svg = 'assets/images/app_icons/sort.svg';
  final String star_svg = 'assets/images/app_icons/star.svg';
}

@immutable
final class _Categories {
  _Categories._();

  final String image1_png = 'assets/images/categories/image1.png';
  final String image2_png = 'assets/images/categories/image2.png';
  final String image3_png = 'assets/images/categories/image3.png';
  final String image4_png = 'assets/images/categories/image4.png';
  final String image5_png = 'assets/images/categories/image5.png';
}

@immutable
final class _Page_view_images {
  _Page_view_images._();

  final String page_view_image_1_svg =
      'assets/images/page_view_images/page_view_image_1.svg';
  final String page_view_image_2_svg =
      'assets/images/page_view_images/page_view_image_2.svg';
}

@immutable
final class _Products {
  _Products._();

  final String product1_png = 'assets/images/products/product1.png';
  final String product2_png = 'assets/images/products/product2.png';
  final String product3_png = 'assets/images/products/product3.png';
  final String product4_png = 'assets/images/products/product4.png';
}

@immutable
final class _Social_media {
  _Social_media._();

  final String bebo_png = 'assets/images/social-media/bebo.png';
  final String darkbebo_png = 'assets/images/social-media/darkBebo.png';
  final String darkfacebook_png = 'assets/images/social-media/darkFacebook.png';
  final String darkfacebookcircled_png =
      'assets/images/social-media/darkFacebookCircled.png';
  final String darkgooglemaps_png =
      'assets/images/social-media/darkGoogleMaps.png';
  final String darkgoogleplus_png =
      'assets/images/social-media/darkGooglePlus.png';
  final String darkinstagram_png =
      'assets/images/social-media/darkInstagram.png';
  final String darklinkedin_png = 'assets/images/social-media/darkLinkedIn.png';
  final String darkreddit_png = 'assets/images/social-media/darkReddit.png';
  final String darkshare_png = 'assets/images/social-media/darkShare.png';
  final String darksnapchat_png = 'assets/images/social-media/darkSnapchat.png';
  final String darktelegram_png = 'assets/images/social-media/darkTelegram.png';
  final String darktiktok_png = 'assets/images/social-media/darkTikTok.png';
  final String darktinder_png = 'assets/images/social-media/darkTinder.png';
  final String darktumblr_png = 'assets/images/social-media/darkTumblr.png';
  final String darktwitter_png = 'assets/images/social-media/darkTwitter.png';
  final String darkyoutube_png = 'assets/images/social-media/darkYoutube.png';
  final String facebook_png = 'assets/images/social-media/facebook.png';
  final String facebookcircled_png =
      'assets/images/social-media/facebookCircled.png';
  final String googlemaps_png = 'assets/images/social-media/googleMaps.png';
  final String googleplus_png = 'assets/images/social-media/googlePlus.png';
  final String instagram_png = 'assets/images/social-media/instagram.png';
  final String linkedin_png = 'assets/images/social-media/linkedIn.png';
  final String reddit_png = 'assets/images/social-media/reddit.png';
  final String share_png = 'assets/images/social-media/share.png';
  final String snapchat_png = 'assets/images/social-media/snapchat.png';
  final String telegram_png = 'assets/images/social-media/telegram.png';
  final String tiktok_png = 'assets/images/social-media/tikTok.png';
  final String tinder_png = 'assets/images/social-media/tinder.png';
  final String tumblr_png = 'assets/images/social-media/tumblr.png';
  final String twitter_png = 'assets/images/social-media/twitter.png';
  final String youtube_png = 'assets/images/social-media/youtube.png';
}

@immutable
final class _Images {
  _Images._();
  final _App_icons app_icons = _App_icons._();
  final _Categories categories = _Categories._();
  final _Page_view_images page_view_images = _Page_view_images._();
  final _Products products = _Products._();
  final _Social_media social_media = _Social_media._();

  final String bgitem_png = 'assets/images/bgItem.png';
  final String bgitem_svg = 'assets/images/bgItem.svg';
  final String imageitem_png = 'assets/images/imageItem.png';
  final String offer_png = 'assets/images/offer.png';
  final String offer_svg = 'assets/images/offer.svg';
}
